// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxxQYxhkhvcbaRa1J_xZwQ4pfqZSrnSc',
    appId: '1:764163665226:web:079fb9f4d22dffd94765b3',
    messagingSenderId: '764163665226',
    projectId: 'clinical-note-e12c5',
    authDomain: 'clinical-note-e12c5.firebaseapp.com',
    storageBucket: 'clinical-note-e12c5.firebasestorage.app',
    measurementId: 'G-MNVGFCRPGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcL-rlzlVKk5gZGdVNWVcnK39zK3G54DY',
    appId: '1:764163665226:android:e4204b464e11a2614765b3',
    messagingSenderId: '764163665226',
    projectId: 'clinical-note-e12c5',
    storageBucket: 'clinical-note-e12c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5KCT5TPkSKMdciilUc1tv5DLyRZ-A_k',
    appId: '1:764163665226:ios:bc9a940d624751b74765b3',
    messagingSenderId: '764163665226',
    projectId: 'clinical-note-e12c5',
    storageBucket: 'clinical-note-e12c5.firebasestorage.app',
    iosBundleId: 'com.example.newClinicalFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo5KCT5TPkSKMdciilUc1tv5DLyRZ-A_k',
    appId: '1:764163665226:ios:bc9a940d624751b74765b3',
    messagingSenderId: '764163665226',
    projectId: 'clinical-note-e12c5',
    storageBucket: 'clinical-note-e12c5.firebasestorage.app',
    iosBundleId: 'com.example.newClinicalFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOxxQYxhkhvcbaRa1J_xZwQ4pfqZSrnSc',
    appId: '1:764163665226:web:78d9636871e68b374765b3',
    messagingSenderId: '764163665226',
    projectId: 'clinical-note-e12c5',
    authDomain: 'clinical-note-e12c5.firebaseapp.com',
    storageBucket: 'clinical-note-e12c5.firebasestorage.app',
    measurementId: 'G-6BHXE6K23Z',
  );
}
